# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171002_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate', models.IntegerField()),
                ('idnumber', models.IntegerField()),
                ('name', models.CharField(max_length=264)),
                ('sex', models.CharField(max_length=264)),
                ('id_index', models.CharField(max_length=264)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 7, 50, 52, 880967, tzinfo=utc)),
        ),
    ]
