# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171003_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 7, 59, 6, 972413, tzinfo=utc)),
        ),
    ]
