# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171003_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 8, 15, 56, 397030, tzinfo=utc)),
        ),
    ]
