# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171003_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='start',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 8, 23, 41, 329806, tzinfo=utc)),
        ),
    ]
