# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171003_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 8, 30, 59, 500574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='graduate',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='idnumber',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='start',
            field=models.CharField(max_length=264),
        ),
    ]
