# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171003_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='job',
            field=models.CharField(default='NA', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_data',
            name='working_place',
            field=models.CharField(default='NA', max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 9, 34, 22, 322891, tzinfo=utc)),
        ),
    ]
