# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20171020_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 9, 50, 8, 245344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='graduate',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='start',
            field=models.CharField(max_length=264),
        ),
    ]
