# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171020_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 9, 52, 52, 359684, tzinfo=utc)),
        ),
    ]
