# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20171022_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 2, 17, 28, 994681, tzinfo=utc)),
        ),
    ]
