# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20171024_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 14, 54, 50, 499496, tzinfo=utc)),
        ),
    ]
