# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171024_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 14, 58, 26, 211560, tzinfo=utc)),
        ),
    ]
