# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20171025_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_data',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 17, 33, 43, 216459, tzinfo=utc)),
        ),
    ]
