# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20171026_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 18, 34, 48, 432116, tzinfo=utc)),
        ),
    ]
