# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20171026_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 4, 17, 51, 806983, tzinfo=utc)),
        ),
    ]
